### ISSUE TITLE
README.md's subnet-> nsg section doesn't render properly on Terraform Registry

### ISSUE THREAD

**Issue by sstjean** [azurenoops/terraform-azurerm-overlays-workload-spoke#20]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

n/a

### Module Version

n/a

### AzureRM Provider Version

n/a

### Affected Resource(s)/Data Source(s)

n/a

### Terraform Configuration Files

```hcl
n/a
```

### tfvars variables values

```hcl
n/a
```

### Debug Output/Panic Output

```shell
n/a
```

### Expected Behaviour

Text should be readable

### Actual Behaviour

It kinda looks like this...

![image](https://github.com/azurenoops/terraform-azurerm-overlays-workload-spoke/assets/7573322/c3022084-7a8c-42da-a32c-8867af7dc66b)

### Steps to Reproduce

Read the README

**Comment by jrspinella** [comment]
Fix #21
